name: 赵孔路的网页  Website of Zhao 
url: https://zhaokonglu22.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8
# Sections on the "people" page.
roles:
  - key: age      # faculty
    name: 年龄 Age
  - key: sex       # grad 
    name: 性别 Sex
  - key:  height          # ugrad
    name: 身高 Height
  - key: class            # collab
    name: 班级 Class


# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: 主页 Home
    link: /
  - title: 家人 Families
    link: /families.html
  - title: 朋友 Friends
    link: /friends.html
